import type { NextPage } from "next";
import fs from "fs";
import path from "path";
import matter from "gray-matter";

import Head from "next/head";
import Image from "next/image";

import * as Styled from "../styles/home";
import PostMeta from "../components/PostMeta/PostMeta";
import { IPostMeta } from "../utils/types";

interface HomeProps {
  posts: IPostMeta[];
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <Styled.Container>
      <Head>
        <title>~/GC_blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Styled.IntroSection>
        This is a beginner friendly tech blog written by a beginner. It is also
        a recap of my journey as a developer.
        <br /> All critics and corrections are welcome!
        <br />
        <strong>CAUTION: This blog is VERY opinionated.</strong>
      </Styled.IntroSection>
      <Styled.ArticlesSection>
        <Styled.ArticleList>
          {posts.map((post: IPostMeta, index: number) => (
            <PostMeta key={`post-meta${index}`} post={post} />
          ))}
        </Styled.ArticleList>
      </Styled.ArticlesSection>
    </Styled.Container>
  );
};

// TODO: fetch from strapi
export async function getStaticProps() {
  const files = fs.readdirSync(path.join("posts"));

  const posts = files.map((filename) => {
    const slug = filename.replace(".md", "");
    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
}

export default Home;
